const actionTypes = {
  ADD_PASSWORD: "ADD_PASSWORD",
  ADD_INCOME: "ADD_INCOME",
  ADD_EXPENSE: "ADD_EXPENSE",
  ADD_BORROWED: "ADD_BORROWED",
  ADD_LENT: "ADD_LENT",
  ADD_DONATION: "ADD_DONATION",
  ADD_HISTORY: "ADD_HISTORY",
  UNDO_TRANSACTION: "UNDO_TRANSACTION",
  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_HISTORY: "RESET_HISTORY",
  RESET_APP: "RESET_APP",
};

export default actionTypes;
